/**
 * Country flag utilities for GMUNC's Status Quo.
 * Auto-generated to map ALL 177+ countries present in our regions database.
 */

const ALPHA3_TO_ALPHA2 = {
  "AFG": "af",
  "ARM": "am",
  "AZE": "az",
  "BGD": "bd",
  "BRN": "bn",
  "BTN": "bt",
  "CHN": "cn",
  "GEO": "ge",
  "IND": "in",
  "IDN": "id",
  "JPN": "jp",
  "KAZ": "kz",
  "KGZ": "kg",
  "KHM": "kh",
  "KOR": "kr",
  "LAO": "la",
  "LKA": "lk",
  "MDV": "mv",
  "MNG": "mn",
  "MMR": "mm",
  "MYS": "my",
  "NPL": "np",
  "PAK": "pk",
  "PHL": "ph",
  "PRK": "kp",
  "SGP": "sg",
  "THA": "th",
  "TJK": "tj",
  "TLS": "tl",
  "TKM": "tm",
  "TWN": "tw",
  "UZB": "uz",
  "VNM": "vn",
  "ATG": "ag",
  "BHS": "bs",
  "BLZ": "bz",
  "BRB": "bb",
  "CAN": "ca",
  "CRI": "cr",
  "CUB": "cu",
  "DMA": "dm",
  "DOM": "do",
  "GRD": "gd",
  "GTM": "gt",
  "HND": "hn",
  "HTI": "ht",
  "JAM": "jm",
  "KNA": "kn",
  "LCA": "lc",
  "MEX": "mx",
  "NIC": "ni",
  "PAN": "pa",
  "SLV": "sv",
  "TTO": "tt",
  "USA": "us",
  "VCT": "vc",
  "ARG": "ar",
  "BOL": "bo",
  "BRA": "br",
  "CHL": "cl",
  "COL": "co",
  "ECU": "ec",
  "GUY": "gy",
  "PER": "pe",
  "PRY": "py",
  "SUR": "sr",
  "URY": "uy",
  "VEN": "ve",
  "ALB": "al",
  "AND": "ad",
  "AUT": "at",
  "BEL": "be",
  "BLR": "by",
  "BIH": "ba",
  "BGR": "bg",
  "HRV": "hr",
  "CYP": "cy",
  "CYN": "cy",
  "CZE": "cz",
  "DNK": "dk",
  "EST": "ee",
  "FIN": "fi",
  "FRA": "fr",
  "DEU": "de",
  "GRC": "gr",
  "HUN": "hu",
  "ISL": "is",
  "IRL": "ie",
  "ITA": "it",
  "KOS": "xk",
  "LVA": "lv",
  "LIE": "li",
  "LTU": "lt",
  "LUX": "lu",
  "MKD": "mk",
  "MLT": "mt",
  "MDA": "md",
  "MNE": "me",
  "NLD": "nl",
  "NOR": "no",
  "POL": "pl",
  "PRT": "pt",
  "ROU": "ro",
  "RUS": "ru",
  "SRB": "rs",
  "SVK": "sk",
  "SVN": "si",
  "ESP": "es",
  "SWE": "se",
  "CHE": "ch",
  "TUR": "tr",
  "UKR": "ua",
  "GBR": "gb",
  "BHR": "bh",
  "EGY": "eg",
  "IRN": "ir",
  "IRQ": "iq",
  "ISR": "il",
  "JOR": "jo",
  "KWT": "kw",
  "LBN": "lb",
  "OMN": "om",
  "PSE": "ps",
  "QAT": "qa",
  "SAU": "sa",
  "SYR": "sy",
  "ARE": "ae",
  "YEM": "ye",
  "AGO": "ao",
  "BEN": "bj",
  "BFA": "bf",
  "BDI": "bi",
  "CMR": "cm",
  "CAF": "cf",
  "TCD": "td",
  "COM": "km",
  "COG": "cg",
  "COD": "cd",
  "CIV": "ci",
  "DJI": "dj",
  "GNQ": "gq",
  "ERI": "er",
  "ETH": "et",
  "GAB": "ga",
  "GMB": "gm",
  "GHA": "gh",
  "GIN": "gn",
  "GNB": "gw",
  "KEN": "ke",
  "LSO": "ls",
  "LBR": "lr",
  "LBY": "ly",
  "MDG": "mg",
  "MWI": "mw",
  "MLI": "ml",
  "MRT": "mr",
  "MUS": "mu",
  "MAR": "ma",
  "MOZ": "mz",
  "NER": "ne",
  "NGA": "ng",
  "RWA": "rw",
  "STP": "st",
  "SEN": "sn",
  "SYC": "sc",
  "SLE": "sl",
  "SOM": "so",
  "ZAF": "za",
  "SSD": "ss",
  "SDN": "sd",
  "SWZ": "sz",
  "TZA": "tz",
  "TGO": "tg",
  "TUN": "tn",
  "UGA": "ug",
  "ZMB": "zm",
  "ZWE": "zw",
  "BWA": "bw",
  "NAM": "na",
  "AUS": "au",
  "FJI": "fj",
  "KIR": "ki",
  "NZL": "nz",
  "PNG": "pg",
  "SLB": "sb",
  "TON": "to",
  "VUT": "vu",
  "WSM": "ws"
};

export function getAlpha2(alpha3) {
  return ALPHA3_TO_ALPHA2[alpha3] || null;
}

export function getFlagUrl(alpha3, format = 'svg', pngWidth = 40) {
  const a2 = ALPHA3_TO_ALPHA2[alpha3];
  if (!a2) return null;

  if (format === 'svg') {
    return `https://flagcdn.com/${a2}.svg`;
  }
  return `https://flagcdn.com/w${pngWidth}/${a2}.png`;
}

export default ALPHA3_TO_ALPHA2;
