export const NEWS_SOURCES = [
  { name: "None", domain: "" },
  { name: "Reuters", domain: "reuters.com" },
  { name: "The Associated Press (AP)", domain: "apnews.com" },
  { name: "Agence France-Presse (AFP)", domain: "afp.com" },
  { name: "BBC News", domain: "bbc.co.uk" },
  { name: "Deutsche Welle (DW)", domain: "dw.com" },
  { name: "Bloomberg News", domain: "bloomberg.com" },
  { name: "Financial Times", domain: "ft.com" },
  { name: "The Wall Street Journal", domain: "wsj.com" },
  { name: "The New York Times", domain: "nytimes.com" },
  { name: "The Washington Post", domain: "washingtonpost.com" },
  { name: "NPR", domain: "npr.org" },
  { name: "PBS NewsHour", domain: "pbs.org" },
  { name: "Politico", domain: "politico.com" },
  { name: "Axios", domain: "axios.com" },
  { name: "Christian Science Monitor", domain: "csmonitor.com" },
  { name: "The Economist", domain: "economist.com" },
  { name: "Time", domain: "time.com" },
  { name: "Newsweek", domain: "newsweek.com" },
  { name: "The Guardian", domain: "theguardian.com" },
  { name: "The Independent", domain: "independent.co.uk" },
  { name: "The Times (UK)", domain: "thetimes.co.uk" },
  { name: "Le Monde", domain: "lemonde.fr" },
  { name: "El País", domain: "elpais.com" },
  { name: "Corriere della Sera", domain: "corriere.it" },
  { name: "Nikkei Asia", domain: "asia.nikkei.com" },
  { name: "The Asahi Shimbun", domain: "asahi.com" },
  { name: "South China Morning Post", domain: "scmp.com" },
  { name: "Al Jazeera English", domain: "aljazeera.com" },
  { name: "The Straits Times", domain: "straitstimes.com" },
  { name: "ABC News (Australia)", domain: "abc.net.au" }
];
